# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
}
b <- board_folder(path = "/var/folders/hv/hzsmmyk9393_m7q3nscx1slc0000gn/T/RtmpkjiCdG/pins-16213956f569")
v <- vetiver_pin_read(b, "hotel_rf")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
